import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import Layout from "@/layouts/DefaultLayout";

import styles from "@/styles/Home.module.css";

interface PageProps {
  projectId: string | null;
}

export const getServerSideProps: GetServerSideProps<PageProps> = async (
  _context
) => {
  return {
    props: {
      projectId: process.env.PROJECT_ID ?? null,
    },
  };
};

const Home: NextPage<PageProps> = (props) => {
  const { data: session, status } = useSession();
  console.log(useSession());

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/slack-forever-frontend/public/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1>Slack log viewer</h1>
          <div>
            {!session && (
              <>
                Not signed in <br />
                <button onClick={signIn}>Sign in</button>
              </>
            )}
            {session && (
              <>
                Signed in as {session.user.email} <br />
                {session.accessToken}
                <br />
                <button onClick={signOut}>Sign out</button>
              </>
            )}
          </div>
        </main>
      </div>
    </Layout>
  );
};

export default Home;
