import Head from 'next/head'
import { signIn, signOut, useSession } from 'next-auth/react'

import DefaultLayout from '@/components/layouts/DefaultLayout'
import Typography from '@mui/material/Typography'

import React from 'react'
import MessagesContainer from '@/components/models/channel-message/MessagesContainer'

export interface Props {
  projectId: string | null
}

const Home: React.FC<Props> = (props) => {
  const { data: session, status } = useSession()
  const date = new Date()

  return (
    <DefaultLayout>
      <Head>
        <title>Slack Forever</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/frontend/public/favicon.ico" />
      </Head>
      <main>
        <MessagesContainer channels={['ai', 'bi']} date={date} />
      </main>
    </DefaultLayout>
  )
}

export default Home
